import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import "./typografi.global.css";
import { AuthProvider } from "./auth.js"
import BootstrapClient from "./components/bootstrap"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  if (typeof window !== "undefined") {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }
  
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <BootstrapClient />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
